@startuml

title __DAO's Class Diagram__\n

  namespace br.com.bancoms.dao {
    class br.com.bancoms.dao.ClienteDAO {
        + ClienteDAO()
        + consultarCliente()
        + realizarLogin()
    }
  }
  

  namespace br.com.bancoms.dao {
    class br.com.bancoms.dao.ContaDAO {
        + ContaDAO()
        + atualizarSaldo()
        + consultarConta()
    }
  }
  

  namespace br.com.bancoms.dao {
    class br.com.bancoms.dao.DatabaseConnect {
        - conexao : Connection
        {static} - databaseConnect : DatabaseConnect
        + closeConnection()
        + closeConnection()
        + getConexao()
        {static} + getInstance()
        + getPreparedSQL()
        + getPreparedSQL()
        + rollBack()
        - DatabaseConnect()
        - abrirConexaoMYSQL()
        - carregarJDBC()
        - setConexao()
    }
  }
  

  namespace br.com.bancoms.dao {
    class br.com.bancoms.dao.MovimentoDAO {
        + MovimentoDAO()
        + getSaldoDiferencial()
        + listarMovimentosPorTipo()
        + listarTodosMovimentos()
        + registrarMovimento()
    }
  }
  

  namespace br.com.bancoms.dao {
    class br.com.bancoms.dao.QueryControl {
        - ps : PreparedStatement
        - rs : ResultSet
        + QueryControl()
        + closePS()
        + closeRS()
        + executeQuery()
        + executeUpdate()
        + getDate()
        + getDouble()
        + getInt()
        + getInt()
        + getString()
        + getTimestamp()
        + next()
        + setDate()
        + setDouble()
        + setGeneratedKeys()
        + setInt()
        + setSQL()
        + setSQL()
        + setString()
        + setTimestamp()
    }
  }
  

  namespace br.com.bancoms.dao {
    enum QUERY {
      RETURN_KEY
    }
  }
  

  namespace br.com.bancoms.dao {
    enum RESULT {
      FAILED
      SUCCESS
    }
  }
  

  br.com.bancoms.dao.QueryControl +-down- br.com.bancoms.dao.QueryControl.QUERY
  br.com.bancoms.dao.QueryControl +-down- br.com.bancoms.dao.QueryControl.RESULT


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
