drop database banco_ms;

CREATE DATABASE IF NOT EXISTS banco_ms ;
USE banco_ms ;

-- -----------------------------------------------------
-- Table `banco_ms`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CLIENTE (
  ID_CLIENTE INT(11) NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  SOBRENOME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_CLIENTE));


-- -----------------------------------------------------
-- Table `banco_ms`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CONTA (
  ID_CONTA INT(11) NOT NULL AUTO_INCREMENT,
  ID_CLIENTE INT(11) NOT NULL,
  TIPO_CONTA INT(11) NOT NULL,
  DESCRICAO_CONTA VARCHAR(100) NOT NULL,
  NUMERO_CONTA INT(11) NOT NULL,
  SENHA VARCHAR(10) NOT NULL,
  SALDO_TOTAL DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID_CONTA),
  CONSTRAINT CLIENTE_CONTA_FK
  FOREIGN KEY (ID_CLIENTE)
  REFERENCES CLIENTE (ID_CLIENTE));


-- -----------------------------------------------------
-- Table `banco_ms`.`movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MOVIMENTO (
  ID_MOVIMENTO INT(11) NOT NULL AUTO_INCREMENT,
  ID_CONTA INT(11) NOT NULL,
  TIPO_MOVIMENTO INT(11) NOT NULL,
  DESCRICAO_TIPO VARCHAR(100) NOT NULL,
  VALOR_MOVIMENTO DECIMAL(10,2) NOT NULL,
  DATA_MOVIMENTO VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID_MOVIMENTO),
  CONSTRAINT CONTA_MOVIMENTO_FK
    FOREIGN KEY (ID_CONTA)
    REFERENCES CONTA (ID_CONTA));
    
 INSERT INTO MOVIMENTO(ID_CONTA,TIPO_MOVIMENTO,DESCRICAO_TIPO,VALOR_MOVIMENTO,DATA_MOVIMENTO) VALUES(1,4,'EMPRÉSTIMO',400.0,'15/03/2019');   
 INSERT INTO EMPRESTIMO(VALOR_EMPRESTADO,VALOR_PARCELADO,QTD_PARCELAS,ID_MOVIMENTO) VALUES(400.0,40.0,10,1);
 
SELECT EMPRESTIMO.VALOR_EMPRESTADO,EMPRESTIMO.VALOR_PARCELADO,EMPRESTIMO.QTD_PARCELAS FROM EMPRESTIMO JOIN MOVIMENTO ON MOVIMENTO.ID_MOVIMENTO = EMPRESTIMO.ID_MOVIMENTO WHERE MOVIMENTO.ID_CONTA = 1 AND MOVIMENTO.TIPO_MOVIMENTO = 4;
 
SELECT * FROM MOVIMENTO;

UPDATE MOVIMENTO SET VALOR_MOVIMENTO = (SELECT (MOVIMENTO.VALOR_MOVIMENTO - EMPRESTIMO.VALOR_PARCELADO) FROM EMPRESTIMO JOIN MOVIMENTO ON MOVIMENTO.ID_MOVIMENTO = EMPRESTIMO.ID_MOVIMENTO
WHERE MOVIMENTO.ID_CONTA = 1 AND MOVIMENTO.TIPO_MOVIMENTO = 4)
WHERE ID_CONTA = 1 AND TIPO_MOVIMENTO = 4;


SELECT CONTA.ID_CONTA,CONTA.TIPO_CONTA,CONTA.DESCRICAO_CONTA, CONTA.SALDO_TOTAL, CLIENTE.NOME, CLIENTE.SOBRENOME from CONTA JOIN CLIENTE ON CONTA.ID_CLIENTE = CLIENTE.ID_CLIENTE WHERE NUMERO_CONTA = (?) and SENHA = (?);
 
-- -----------------------------------------------------
-- Table `banco_ms`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EMPRESTIMO (
  ID_EMPRESTIMO INT NOT NULL AUTO_INCREMENT,
  VALOR_EMPRESTADO DECIMAL(10,2) NOT NULL,
  VALOR_PARCELADO DECIMAL(10,2) NOT NULL,
  QTD_PARCELAS INT(10) NOT NULL,
  ID_MOVIMENTO INT(11) NOT NULL,
  PRIMARY KEY (ID_EMPRESTIMO),
  CONSTRAINT fk_emprestimo_movimento1
    FOREIGN KEY (ID_MOVIMENTO)
    REFERENCES MOVIMENTO (ID_MOVIMENTO));


INSERT INTO CLIENTE VALUES(1,'Mateus','da Silva Santos');
INSERT INTO CLIENTE VALUES(2,'Ricardo','Santos');
INSERT INTO CLIENTE VALUES(3,'Junior','Simões Oliveira');


INSERT INTO CONTA VALUES(1,1,1,'CONTA-CORRENTE',123456,'123a',1000);
INSERT INTO CONTA VALUES (2,2,2,'CONTA-POUPANÇA',1234567,'124B',1000);
INSERT INTO CONTA VALUES (3,3,3,'CONTA-INVESTIMENTO',12345678,'125C',1000);
SELECT * FROM Cliente;



select * from conta;

DELETE FROM MOVIMENTO WHERE ID_MOVIMENTO = 3;

SELECT DATA_MOVIMENTO,DESCRICAO_TIPO,VALOR_MOVIMENTO
FROM MOVIMENTO WHERE TIPO_MOVIMENTO in (1,2) AND ID_CONTA = (?) order by  DATA_MOVIMENTO desc limit 8;

INSERT INTO MOVIMENTO (ID_CONTA,TIPO_MOVIMENTO,DESCRICAO_TIPO,VALOR_MOVIMENTO,DATA_MOVIMENTO) VALUES (1,2,'DEPOSITO',1000.00,'20/03/2019');